# Generated by Django 5.0.2 on 2024-02-17 22:33

from django.db import migrations


def create_data(apps, schema_editor):
    JobOffer = apps.get_model('job_application', 'JobOffer')
    JobOffer(title="Oferta pracy", responsibilities="Pracowac", requirements="Brak", link="https://www.pracuj.pl/praca?utm_source=bing&utm_medium=cpc&utm_campaign=ongoing&utm_term=search&utm_content=brand&campaignid=483601975&adgroupid=1235852083812554&keyword=pracuj.pl&twdnt=o&msclkid=5d42ccc88b921ff5c095a919bf653390").save()


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]